service: WL-infrastructure
frameworkVersion: ">=1.60.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  tags:
    project: WatchListApp
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource:
      - '*'

custom:
  stage: dev
  generalTableName: WatchListAppTBL
  projectName: WatchListApp

plugins:
  - serverless-offline
  - serverless-webpack

resources:
  - ${file(resources/dynamodb.yml)}
  - ${file(resources/cognito.yml)}
  - ${file(resources/api-gateway.yml)}

functions:
  temp:
    handler: src/handler.temp
    events:
      - http:
          path: /test
          method: get